import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  id(i) { return `1020001000${i}` },
  businessApp() { return Math.ceil(Math.random() * 300) },
  businessBrowser() { return Math.ceil(Math.random() * 300) },
  pageViewApp() { return Math.ceil(Math.random() * 300) },
  pageViewBrowser() { return Math.ceil(Math.random() * 300) },
  scoopsApp() { return Math.ceil(Math.random() * 300) },
  scoopsBrowser() { return Math.ceil(Math.random() * 300) },
  visitWebsiteApp() { return Math.ceil(Math.random() * 300) },
  visitWebsiteBrowser() { return Math.ceil(Math.random() * 300) },
  visitTwitterApp() { return Math.ceil(Math.random() * 300) },
  visitTwitterBrowser() { return Math.ceil(Math.random() * 300) },
  visitFacebookApp() { return Math.ceil(Math.random() * 300) },
  visitFacebookBrowser() { return Math.ceil(Math.random() * 300) },
  visitInstagramApp() { return Math.ceil(Math.random() * 300) },
  visitInstagramBrowser() { return Math.ceil(Math.random() * 300) },
  mapClickApp() { return Math.ceil(Math.random() * 300) },
  mapClickBrowser() { return Math.ceil(Math.random() * 300) },
  viewSocialApp() { return Math.ceil(Math.random() * 300) },
  viewSocialBrowser() { return Math.ceil(Math.random() * 300) },
  phoneHotlinkApp() { return Math.ceil(Math.random() * 300) },
  phoneHotlinkBrowser() { return Math.ceil(Math.random() * 300) },
  shareScoopFacebookApp() { return Math.ceil(Math.random() * 300) },
  shareScoopFacebookBrowser() { return Math.ceil(Math.random() * 300) },
  shareScoopTwitterApp() { return Math.ceil(Math.random() * 300) },
  shareScoopTwitterBrowser() { return Math.ceil(Math.random() * 300) },
  shareScoopEmailApp() { return Math.ceil(Math.random() * 300) },
  shareScoopEmailBrowser() { return Math.ceil(Math.random() * 300) },
  clickScoopHotlinkApp() { return Math.ceil(Math.random() * 300) },
  clickScoopHotlinkBrowser() { return Math.ceil(Math.random() * 300) },
  clickScoopMarqueeApp() { return Math.ceil(Math.random() * 300) },
  clickScoopMarqueeBrowser() { return Math.ceil(Math.random() * 300) },
  marqueeScoopImpressionApp() { return Math.ceil(Math.random() * 300) },
  marqueeScoopImpressionBrowser() { return Math.ceil(Math.random() * 300) }
});
